version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: minio server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: storageadmin
      MINIO_ROOT_PASSWORD: supersecret
    volumes:
      - minio-data:/data
    restart: always

volumes:
  minio-data:
